version: '3.7'

services:
  app:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: app-front
    volumes: 
      - .:/app
    working_dir: /app
    ports:
      - 8080:8080
    environment: 
      - CHOKIDAR_USEPOLLING=true